# << ======================================================================= >> 
# <<                            TEMPLATE CONFIG                              >> 
# << ======================================================================= >> 
# This is the Jekyll build config file.
# Much of this should only be touched if you know what you are doing !!
# That being said the first two sections are set up for you to be able to fill out easily,
#  and you will need to fill out at least the first section to get this to work !!

# << ========================== Required Section =========================== >> 
# this is displayed on the page header of every page & in the page metadata.
title:              "${ProjName}"
# this is displayed on the about page
bio:                'This is a research page for publications and software created under Prof. Ganesh Gopalakrishnan’s guidance, for the ${ProjName} project.'
# this is displayed on the about page & in the page metadata
description:        "This is a research page for publications and software created under Prof. Ganesh Gopalakrishnan’s guidance, for the Comport ${ProjName} project."
# The location & language information for the site (part of the site metadata)
locale:             en_US

# These next two fields will depend on how you are hosting the webpage.
# If you plan to build locally you might need to fill them in with the proper info 
#  to get links ot build correctly, across the entire site.
# This is also true if you want to build locally but still host on GitHub Pages. 
#  see https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites
# However if you plan to build and host on GitHub Pages you are fine to leave these commented out as GitHub compensates.
# url:                "https://osterhoutan-UofU.github.io" # the base hostname & protocol for your site #! Replace me later
# baseurl:            "comweb" # the subpath of your site, e.g. /blog #! will likely need replace me latter too


# << ========================== Optional Section =========================== >> 
# This section has information that will add to the website 
#  and make it seem more professional.
# Sections of importance will have descriptions,
#  but most should be self explanatory.
# To activate a section uncomment it, and the relevant subsections, 
#   or if the value is set to false, change the value to your desired value (not to true).
# To de-activate a section comment it out, and the relevant subsections.

# This section will display useful links at the bottom of the page to useful resources.
links: 
  docs:             false # URL to page containing documentation for one thing or another (this will also be added to the nav bar)
  email:            false # primary contact email address for the entire proj
  phone:            false # primary contact phone number for the entire proj [phone number must follow the URI tel notation without the `tel:` prefix]
  fax:              false # primary contact fax number for the entire proj (you are really old if you use this) [fax number must follow the URI fax/tel notation without the `fax:` prefix]
  website:          false # URL to a separate website for the proj (maybe official university page, etc.)
  github:           false # bitbucket user or org name
  gitlab:           false # gitlab user or org name
  gitlab_url:       false # URL to self hosted gitlab org (this will supersede the normal gitlab)
  bitbucket:        false # bitbucket user or org name
  repo:             false # URL to other repo system that you use (this is a catch all)
  reddit:           false # sub-reddit name (prepend "r/" for sub-reddit or "u/" for a user)
  forum:            false # URL to a help forum (i.e. repo issues page or an actual forum)
  youtube:          false # youtube channel URL
  vimeo:            false # vimeo channel name (who even are you?)
  twitter:          false # twitter handle (if you add this you're probably annoying)
  instagram:        false # instagram profile name (if you add this you're a bad person)
  facebook:         false # facebook page name (if you add this you're old)



# << ======================================================================= >> 
# <<                             EXPERT SECTION                              >> 
# << ======================================================================= >> 
# This is the section that you should only tough if you know what you are doing !!

# Collections
# collections_dir: site-contents
collections:
  blog:
    output          : true
    future          : true
    blog            : true
    # collections_dir : blog
    # collections_dir : site-content/blog
    permalink       : /:collection/:name
  people:
    output          : true
    people          : true
    # collections_dir : people
    # collections_dir : site-content/people
    permalink       : /:collection/:name
  education:
    output          : true
    education       : true
    # collections_dir : site
    # collections_dir : site-content/education
    permalink       : /:collection/:name
  software:
    output          : true
    software        : true
    # collections_dir : software
    # collections_dir : site-content/software
    permalink       : /:collection/:name

defaults:
  - scope:
      path        : publications/downloads
    values:
      type        : download
      publication : true
      tags        : [publication, download, document, pdf, scholarship]
  - scope:
      path        : software/downloads
    values:
      type        : download
      software    : true
      tags        : [software, download]
  - scope:
      path        : education/downloads
    values:
      type        : download
      education   : true
      tags        : [education, talk, resource, download]
  - scope:
      path        : education/downloads
    values:
      type        : download
      education   : true
      tags        : [education, talk, resource, download]



      # permalink: /comport/blog/:year/:month/:day/:title/ #! Fix me later
  # - scope:
  #     path: './pubs.bib'
  #   values:
  #     permalink: /pubs.bib
  #     bib: true
  # - scope:
  #     path: './references.bib'
  #   values:
  #     permalink: /references.bib
  #     bib: true



# Jekyll
# theme:              jekyll-theme-slate
# permalink:          /blog/:catagories/:year/:month/:day/:title/  #! Fix me later
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"

# personal
location:           Salt Lake City, UT
phone:              (801) 581-8224
#email:              info@default.com


# notes about supported version id's are as of 2021-06-25 (see current status on https://pages.github.com/versions/) 
plugins:
  - jekyll-mentions   # YES (v1.6.0)
  - jekyll-sitemap    # YES (v1.4.0)
  - jekyll-feed       # YES (v0.15.1)
  - jekyll-gist       # YES (v0.15.1)
  # - jekyll-paginate   # YES (v1.1.0)
  # - jekyll-scholar    # ! NO !  (this one hurts as we use it's functionality a lot)
  # - jekyll-maps       # ! NO ! (but this only needs to generate one page so just move the gen content to includes)


# paginate: 6
# paginate_path: "/blog/page:num/" #! Fix me later

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, docs, src, vendor, CNAME, LICENSE, Rakefile, old, .old, scripts, par_site_tar.gz, fv_site_tar.gz, update_log.txt, .vscode, .mypy_cache, update_scripts, site-src]
# include: [site-content/_posts, site-content/_people, site-content/_software, site-content/_education, _posts, _people, _software, _education]
